export enum SmartRecycleBinStatus {
    HEALTHY = "HEALTHY",
    IN_CONSTRUCTION = "IN_CONSTRUCTION",
    FIXING = "FIXING",
    LOST_CONNECTION = "LOST_CONNECTION",
    ERROR = "ERROR",
    NO_LONGER_NEEDED = "NO_LONGER_NEEDED",
}

export enum PhysicalRecycleBinStatus {
    NORMAL = "NORMAL",
    FULL = "FULL",
}

export enum WasteType {
    RECYCLABLE = "RECYCLABLE",
    ORGANIC = "ORGANIC",
    NON_RECYCLABLE = "NON_RECYCLABLE",
}

export const WasteClassificationMap = {
    aerosol_cans: "Bình xịt",
    aluminum_food_cans: "Lon thực phẩm",
    aluminum_soda_cans: "Lon nước ngọt",
    steel_food_cans: "Lon thực phẩm",
    cardboard_boxes: "Hộp giấy",
    cardboard_packaging: "Bao bì giấy",
    magazines: "Tạp chí",
    newspaper: "Báo",
    office_paper: "Giấy văn phòng",
    paper_cups: "Ly giấy",
    glass_beverage_bottles: "Chai thủy tinh",
    glass_cosmetic_containers: "Chai thủy tinh",
    glass_food_jars: "Chai thủy tinh",
    plastic_detergent_bottles: "Chai nhựa",
    plastic_food_containers: "Chai nhựa",
    plastic_soda_bottles: "Chai nhựa",
    plastic_water_bottles: "Chai nhựa",
    coffee_grounds: "Cà phê",
    eggshells: "Vỏ trứng",
    food_waste: "Thức ăn thừa",
    tea_bags: "Túi trà",
    clothing: "Quần áo",
    disposable_plastic_cutlery: "Đồ ăn nhựa",
    plastic_cup_lids: "Nắp ly nhựa",
    plastic_shopping_bags: "Túi nhựa",
    plastic_straws: "Ống hút nhựa",
    plastic_trash_bags: "Túi rác nhựa",
    shoes: "Giày",
    styrofoam_cups: "Ly nhựa",
    styrofoam_food_containers: "Hộp thức ăn",
};

export const WasteClassification: Record<WasteType, string[]> = {
    [WasteType.RECYCLABLE]: [
        "aerosol_cans",
        "aluminum_food_cans",
        "aluminum_soda_cans",
        "steel_food_cans",
        "cardboard_boxes",
        "cardboard_packaging",
        "magazines",
        "newspaper",
        "office_paper",
        "paper_cups",
        "glass_beverage_bottles",
        "glass_cosmetic_containers",
        "glass_food_jars",
        "plastic_detergent_bottles",
        "plastic_food_containers",
        "plastic_soda_bottles",
        "plastic_water_bottles",
    ],
    [WasteType.ORGANIC]: ["coffee_grounds", "eggshells", "food_waste", "tea_bags"],
    [WasteType.NON_RECYCLABLE]: [
        "clothing",
        "disposable_plastic_cutlery",
        "plastic_cup_lids",
        "plastic_shopping_bags",
        "plastic_straws",
        "plastic_trash_bags",
        "shoes",
        "styrofoam_cups",
        "styrofoam_food_containers",
    ],
};
